[build]
  command = "npm ci --prefer-offline && npm run build"
  publish = "dist/public"
  functions = "netlify/functions"
  # Add ignore command to skip builds when no relevant files changed
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./client/ ./server/ ./shared/ package.json vite.config.ts"

[build.environment]
  # Specify Node version to match your development environment
  NODE_VERSION = "20"
  # Optimize npm install during build
  NPM_FLAGS = "--no-audit --production=false"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 9000
  targetPort = 5002

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Cache headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Add CORS headers to prevent API issues
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

# API redirects to serverless functions - MUST come BEFORE the SPA catch-all
# High-priority specific redirects for critical endpoints
[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200
  force = true

[[redirects]]
  from = "/api/leaderboard"
  to = "/.netlify/functions/leaderboard"
  status = 200
  force = true

# Protocol API endpoints
[[redirects]]
  from = "/api/protocol/metrics"
  to = "/.netlify/functions/protocol-metrics"
  status = 200
  force = true

[[redirects]]
  from = "/api/protocol/proposals"
  to = "/.netlify/functions/protocol-proposals"
  status = 200
  force = true

# General API redirect for other endpoints as fallback
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # Ensure this redirect always happens

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
