[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5000
  targetPort = 5000

# Handle SPA routing by redirecting all paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
